project_id       = "products-422104"
region           = "us-east1"
zone             = "us-east1-b"
image_id         = "debian-cloud/debian-11"
public_key_path  = "~/.ssh/id_rsa.pub"
key_name         = "id_rsa"
